"""
build_QUBO.py
─────────────────────────────────────────────────────────────────────────────
Builds a 96×96 upper-triangular QUBO weight matrix W from:
  • uni_results.tsv   — unimolecular EMT/DFT results (96 rows)
  • bi_results.tsv    — bimolecular EMT/DFT results  (4560 rows)
  • pairs_manifest.csv — maps pair_idx → site1_idx, site2_idx
                         (generated by site_find_2CO.py)

Input TSV format (both files, same layout)
──────────────────────────────────────────
  # comment lines starting with # are skipped
  # key metadata lines parsed:
  #   E_slab  = -227.186127 eV
  #   E_CO    = -13.769071 eV
  # column header line starts with "# filename"  (note the leading #)
  # data lines: whitespace-separated, no leading #

  filename              E_total_eV   E_ads_eV   steps  time_s  converged
  site001_ontop_Pd.vasp -241.704708  -0.749510  4      2.4     True

Site index extracted from filename:
  uni : site001_ontop_Pd.vasp        → site_idx = 1
  bi  : pair0001_ontop_Pd__...vasp   → pair_idx = 1
        pair_idx → (site1_idx, site2_idx) looked up from pairs_manifest.csv

QUBO convention
───────────────
  W[i,i] = E_ads(i)                                     diagonal
  W[i,j] = (E_ads_bi(i,j) − E_ads(i) − E_ads(j)) / 2   upper triangle i<j
  W[i,j] = 0                                             lower triangle i>j

Outputs  →  QUBO_output/
  QUBO_matrix.npy        numpy binary  (fast reload)
  QUBO_matrix.csv        96×96 with site-label headers
  QUBO_summary.txt       statistics, top repulsive/attractive pairs
─────────────────────────────────────────────────────────────────────────────
"""

import numpy as np
import re, csv, os

# ═══════════════════════════════════════════════════════════════════════════
#  USER SETTINGS
# ═══════════════════════════════════════════════════════════════════════════
UNI_TSV      = "uni_results.tsv"
BI_TSV       = "bi_results.tsv"
MANIFEST_CSV = "CO2_adsorbed/pairs_manifest.csv"   # from site_find_2CO.py
OUTPUT_DIR   = "QUBO_output"
N_SITES      = 96
ENERGY_COL   = "E_ads_eV"    # column to use: "E_ads_eV" or "E_total_eV"
# ═══════════════════════════════════════════════════════════════════════════

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ─── helpers ─────────────────────────────────────────────────────────────────

def parse_tsv(path):
    """
    Parse a results TSV that has:
      • lines starting with '#' as comments / metadata
      • the column-header line formatted as '# filename  E_total_eV  …'
      • data lines with no leading '#'

    Returns
    -------
    meta   : dict  of key→float parsed from '# KEY = VALUE eV' lines
    header : list  of column names
    rows   : list  of dicts  {col: value}
    """
    meta   = {}
    header = None
    rows   = []

    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue

            if line.startswith("#"):
                # Try to parse  "# KEY = VALUE eV"
                m = re.match(r"#\s*(\S+)\s*=\s*([+-]?\d+\.\d+)", line)
                if m:
                    meta[m.group(1)] = float(m.group(2))

                # Column header line: "# filename   E_total_eV …"
                if "filename" in line:
                    header = line.lstrip("#").split()
                continue

            # Data line
            if header is None:
                raise ValueError(f"Data line found before header in {path}")
            parts = line.split()
            rows.append(dict(zip(header, parts)))

    return meta, header, rows


def site_idx_from_uni_filename(fname):
    """site001_ontop_Pd.vasp  →  1  (1-based)"""
    m = re.match(r"site(\d+)", fname)
    if not m:
        raise ValueError(f"Cannot parse site index from filename: {fname}")
    return int(m.group(1))


def pair_idx_from_bi_filename(fname):
    """pair0001_ontop_Pd__bridge_Pd-Zn_d2.7A.vasp  →  1  (1-based)"""
    m = re.match(r"pair(\d+)", fname)
    if not m:
        raise ValueError(f"Cannot parse pair index from filename: {fname}")
    return int(m.group(1))


# ─── 1. Load pairs manifest ──────────────────────────────────────────────────

print(f"\nLoading pairs manifest: {MANIFEST_CSV} …")
pair_to_sites  = {}   # pair_idx(1-based) → (site1_idx, site2_idx)  0-based
pair_to_labels = {}

with open(MANIFEST_CSV, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pidx = int(row["pair_idx"])
        i    = int(row["site1_idx"]) - 1   # → 0-based
        j    = int(row["site2_idx"]) - 1
        pair_to_sites[pidx]  = (i, j)
        pair_to_labels[pidx] = (row["site1_label"].strip(),
                                row["site2_label"].strip())

print(f"  ✓  {len(pair_to_sites)} pairs loaded from manifest")


# ─── 2. Load unimolecular results ────────────────────────────────────────────

print(f"\nLoading unimolecular results: {UNI_TSV} …")
meta_uni, _, uni_rows = parse_tsv(UNI_TSV)

if meta_uni:
    print(f"  Metadata: " +
          "  ".join(f"{k} = {v} eV" for k, v in meta_uni.items()))

E_uni  = np.full(N_SITES, np.nan)
labels = [""] * N_SITES

skipped_uni = 0
for row in uni_rows:
    if row.get("converged", "True") == "False":
        skipped_uni += 1
        continue
    idx         = site_idx_from_uni_filename(row["filename"]) - 1  # 0-based
    E_uni[idx]  = float(row[ENERGY_COL])
    # extract label from filename: site001_ontop_Pd.vasp → ontop_Pd
    labels[idx] = re.sub(r"\.vasp$", "",
                  re.sub(r"^site\d+_", "", row["filename"]))

missing_uni = np.where(np.isnan(E_uni))[0]
if len(missing_uni):
    raise ValueError(
        f"Missing unimolecular energies for sites (0-based idx): {missing_uni.tolist()}\n"
        f"  Check for unconverged calculations or missing rows.")

print(f"  ✓  {N_SITES} sites loaded  "
      f"(skipped {skipped_uni} unconverged)")
print(f"     {ENERGY_COL}  min={E_uni.min():.4f}  "
      f"max={E_uni.max():.4f}  mean={E_uni.mean():.4f} eV")


# ─── 3. Load bimolecular results ─────────────────────────────────────────────

print(f"\nLoading bimolecular results: {BI_TSV} …")
meta_bi, _, bi_rows = parse_tsv(BI_TSV)

E_bi      = np.full((N_SITES, N_SITES), np.nan)
skipped_bi = 0

for row in bi_rows:
    if row.get("converged", "True") == "False":
        skipped_bi += 1
        continue
    pidx    = pair_idx_from_bi_filename(row["filename"])
    if pidx not in pair_to_sites:
        raise ValueError(f"pair_idx {pidx} not found in manifest.")
    i, j    = pair_to_sites[pidx]
    e       = float(row[ENERGY_COL])
    E_bi[i, j] = e
    E_bi[j, i] = e   # symmetric for easy lookup

expected_pairs = N_SITES * (N_SITES - 1) // 2
loaded_pairs   = int(np.sum(~np.isnan(E_bi[np.triu_indices(N_SITES, k=1)])))

if loaded_pairs != expected_pairs:
    missing_bi = []
    for i in range(N_SITES):
        for j in range(i+1, N_SITES):
            if np.isnan(E_bi[i, j]):
                missing_bi.append((i+1, j+1))
    print(f"  ✗  {len(missing_bi)} pairs missing.  "
          f"First 10: {missing_bi[:10]}")
    if skipped_bi > 0:
        print(f"     ({skipped_bi} pairs skipped as unconverged — "
              f"fill these before final QUBO)")
    # Fill missing with 0 lateral interaction as placeholder so matrix
    # can still be inspected; a warning is printed.
    print("  ⚠  Filling missing off-diagonal entries with "
          "(E_uni_i + E_uni_j) so W[i,j]=0 (no interaction assumed).")
    for i, j in missing_bi:
        E_bi[i-1, j-1] = E_uni[i-1] + E_uni[j-1]
        E_bi[j-1, i-1] = E_bi[i-1, j-1]
else:
    print(f"  ✓  {loaded_pairs} pairs loaded  (all {expected_pairs} present, "
          f"skipped {skipped_bi} unconverged)")

print(f"     {ENERGY_COL}  min={np.nanmin(E_bi):.4f}  "
      f"max={np.nanmax(E_bi):.4f} eV")


# ─── 4. Build QUBO matrix ────────────────────────────────────────────────────

print("\nBuilding QUBO matrix …")
W = np.zeros((N_SITES, N_SITES))

# Diagonal
for i in range(N_SITES):
    W[i, i] = E_uni[i]

# Upper triangle
for i in range(N_SITES):
    for j in range(i + 1, N_SITES):
        W[i, j] = (E_bi[i, j] - E_uni[i] - E_uni[j]) / 2

# Lower triangle stays 0

# Verify lower triangle is zero
assert np.all(W[np.tril_indices(N_SITES, k=-1)] == 0), \
    "Lower triangle is not zero — bug in matrix construction."

diag  = np.diag(W)
upper = W[np.triu_indices(N_SITES, k=1)]

print(f"  ✓  Matrix built  ({N_SITES}×{N_SITES})")
print(f"\n  Diagonal  (W[i,i] = E_ads_uni):")
print(f"    min={diag.min():.4f}  max={diag.max():.4f}  "
      f"mean={diag.mean():.4f} eV")
print(f"\n  Upper triangle  (W[i,j] = lateral interaction / 2):")
print(f"    min={upper.min():.4f}  max={upper.max():.4f}  "
      f"mean={upper.mean():.6f} eV")
print(f"    repulsive  (>0)   : {np.sum(upper > 0):>6}")
print(f"    attractive (<0)   : {np.sum(upper < 0):>6}")
print(f"    near-zero (|w|<1e-3): {np.sum(np.abs(upper)<1e-3):>6}")


# ─── 5. Save outputs ─────────────────────────────────────────────────────────

# 5a. numpy binary
npy_path = os.path.join(OUTPUT_DIR, "QUBO_matrix.npy")
np.save(npy_path, W)
print(f"\n  Saved: {npy_path}")

# 5b. CSV with site-label headers
csv_path = os.path.join(OUTPUT_DIR, "QUBO_matrix.csv")
with open(csv_path, "w", newline="") as f:
    writer = csv.writer(f)
    header = [""] + [f"{i+1}:{labels[i]}" for i in range(N_SITES)]
    writer.writerow(header)
    for i in range(N_SITES):
        writer.writerow([f"{i+1}:{labels[i]}"] +
                        [f"{W[i,j]:.6f}" for j in range(N_SITES)])
print(f"  Saved: {csv_path}")

# 5c. Summary text
txt_path = os.path.join(OUTPUT_DIR, "QUBO_summary.txt")
ui  = np.triu_indices(N_SITES, k=1)
flat = sorted(zip(W[ui], ui[0], ui[1]), reverse=True)

with open(txt_path, "w") as f:
    def w(s=""): f.write(s + "\n")
    w("QUBO MATRIX SUMMARY")
    w("="*72)
    w(f"  Energy column used : {ENERGY_COL}")
    w(f"  Matrix shape       : {N_SITES} × {N_SITES}")
    w(f"  Diagonal entries   : {N_SITES}   (E_uni per site)")
    w(f"  Upper-tri entries  : {len(upper)}  (lateral interactions)")
    w(f"  Lower-tri entries  : 0  (by convention)")
    if meta_uni:
        w()
        for k, v in meta_uni.items():
            w(f"  {k} = {v} eV")
    w()

    w("DIAGONAL  (W[i,i] = E_uni(i), sorted most→least stable)")
    w("-"*72)
    w(f"  {'#':<4} {'idx':>4}  {'Label':<30}  {ENERGY_COL:>12}")
    for rank, idx in enumerate(np.argsort(diag), 1):
        w(f"  {rank:<4} {idx+1:>4}  {labels[idx]:<30}  {diag[idx]:>12.6f}")
    w()

    w("TOP 20 MOST REPULSIVE PAIRS  (largest positive W[i,j])")
    w("-"*72)
    w(f"  {'#':<4} {'i':>4} {'j':>4}  {'Label-i':<28}  {'Label-j':<28}  {'W[i,j]':>10}")
    for rank, (wval, i, j) in enumerate(flat[:20], 1):
        w(f"  {rank:<4} {i+1:>4} {j+1:>4}  {labels[i]:<28}  {labels[j]:<28}  {wval:>10.6f}")
    w()

    w("TOP 20 MOST ATTRACTIVE PAIRS  (most negative W[i,j])")
    w("-"*72)
    w(f"  {'#':<4} {'i':>4} {'j':>4}  {'Label-i':<28}  {'Label-j':<28}  {'W[i,j]':>10}")
    for rank, (wval, i, j) in enumerate(reversed(flat[-20:]), 1):
        w(f"  {rank:<4} {i+1:>4} {j+1:>4}  {labels[i]:<28}  {labels[j]:<28}  {wval:>10.6f}")

print(f"  Saved: {txt_path}")

# ─── 6. Reload snippet ───────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"  Done.  QUBO matrix → ./{OUTPUT_DIR}/")
print(f"\n  Quick reload:")
print(f"    import numpy as np")
print(f"    W = np.load('{npy_path}')   # shape ({N_SITES},{N_SITES})")
print(f"    # W[i,i]  = E_uni site i+1")
print(f"    # W[i,j]  = lateral interaction  (i<j only; j<i → 0)")
print(f"{'='*60}\n")
